<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9667" started-at="2019-04-25T08:53:15Z" finished-at="2019-04-25T08:53:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9667" started-at="2019-04-25T08:53:15Z" finished-at="2019-04-25T08:53:25Z">
      <class name="test.Twittter">
        <test-method status="PASS" signature="setup()[pri:0, instance:test.Twittter@5c1b0d41]" name="setup" is-config="true" duration-ms="15382" started-at="2019-04-25T14:23:00Z" finished-at="2019-04-25T14:23:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getUsers()[pri:0, instance:test.Twittter@5c1b0d41]" name="getUsers" duration-ms="8626" started-at="2019-04-25T14:23:15Z" description="This will give users " finished-at="2019-04-25T14:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsers -->
        <test-method status="FAIL" signature="test()[pri:0, instance:test.Twittter@5c1b0d41]" name="test" duration-ms="1002" started-at="2019-04-25T14:23:24Z" description="This method will fetch the maximum retry count" finished-at="2019-04-25T14:23:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at test.Twittter.test(Twittter.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- test.Twittter -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
